import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'

const Container = styled.div`
  padding: 0 2rem;
`
const Main = styled.main`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;  padding: 0 2rem;
`
const Footer = styled.footer`
  display: flex;
  flex: 1;
  padding: 2rem 0;
  border-top: 1px solid #eaeaea;
  justify-content: center;
  align-items: center;
`

const FooterA = styled.a`
  display: flex;
  justify-content: center;
  align-items: center;
  flex-grow: 1;
`
const Title = styled.h1`
  padding: 0 2rem;
  text-align: center;
  margin: 0;
  line-height: 1.15;
  font-size: 4rem;
`
const TitleA = styled.a`
  color: #0070f3;
  text-decoration: none;
  &:hover,
  &:focus,
  &:active {
    text-decoration: underline;
  }
`

const Logo = styled.span`
  height: 1em;
  margin-left: 0.5rem;
`

const Description = styled.p`
  margin: 4rem 0;
  line-height: 1.5;
  font-size: 1.5rem;
  text-align:center;
`
const Code = styled.code`
  background: #fafafa;
  border-radius: 5px;
  padding: 0.75rem;
  font-size: 1.1rem;
  font-family: Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono,
    Bitstream Vera Sans Mono, Courier New, monospace;
`

const Grid = styled.code`
  display: flex;
  align-items: center;
  justify-content: center;
  flex-wrap: wrap;
  max-width: 800px;
`
const Card = styled.a`
  margin: 1rem;
  padding: 1.5rem;
  text-align: left;
  color: inherit;
  text-decoration: none;
  border: 1px solid #eaeaea;
  border-radius: 10px;
  transition: color 0.15s ease, border-color 0.15s ease;
  max-width: 300px;
  &:hover,
  &:focus,
  &:active {
    color: #0070f3;
    border-color: #0070f3;
  }
`
const CardH2 = styled.h2`
  margin: 0 0 1rem 0;
  font-size: 1.5rem;
`

const CardP = styled.p`
  margin: 0;
  font-size: 1.25rem;
  line-height: 1.5;
`

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Title>
          Welcome to <TitleA href="https://nextjs.org">Next.js!</TitleA>
        </Title>

        <Description>
          Get started by editing{' '}
          <Code>pages/index.tsx</Code>
        </Description>

        <Grid>

          <Card href="https://nextjs.org/docs">
            <CardH2>Documentation &rarr;</CardH2>
            <CardP>Find in-depth information about Next.js features and API.</CardP>
          </Card>

          <Card href="https://nextjs.org/learn">
            <CardH2>Learn &rarr;</CardH2>
            <CardP>Learn about Next.js in an interactive course with quizzes!</CardP>
          </Card>

          <Card href="https://github.com/vercel/next.js/tree/canary/examples">
            <CardH2>Examples &rarr;</CardH2>
            <CardP>Discover and deploy boilerplate example Next.js projects.</CardP>
          </Card>

          <Card href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <CardH2>Deploy &rarr;</CardH2>
            <CardP>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </CardP>
          </Card>
        </Grid>
      </Main>

      <Footer>
        <FooterA
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <Logo>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </Logo>
        </FooterA>
      </Footer>
    </Container>
  )
}

export default Home
